---
title: "Fun Data Visualizations"
author: "Silas Jackson"
date: "5/6/2021"
summary: Some pretty data visualzations.
slug: data-visualizations
linktitle: "Fun Data Visualizations"
output:
  blogdown::html_page:
    toc: true
menu:
  blog:
    parent: Posts
    weight: 1
type: posts
editor_options: 
  chunk_output_type: inline
lastmod: '2021-04-24T23:09:32-04:00'
shiny: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r Libraries, include = FALSE}
library(tidyverse)
library(tm)  
library(viridis)

library(vapoRwave)
library(plotly)
library(ggwordcloud)
library(wordcloud2)
library(ggthemes)

library(extrafont)
library(gganimate)
library(ggpubr)
library(png)
library(stringr)
library(cowplot)

library(magick)
library(gridExtra)
library(jpeg)
library(tidytext)
library(tm)
library(pacman)
library(grid)
library(gridExtra)




windowsFonts("a dripping marker" = windowsFont("a dripping marker"))
```

```{r Load Data, include = FALSE}

load("Movies_Data.Rdata")

```


```{r Comedy}
subset(data.w.genre.ratings, Comedy == 1) %>% 
  arrange(desc(avg_rating)) %>% 
  slice(1:5) %>% 
  ggplot(aes(original_title, avg_rating, label = round(avg_rating, 2))) +
  geom_point(color = "blue") +
  geom_label(color = "blue", vjust = -0.5) +
  labs(title = "Top 5 Comedy Movies by Average IMDB User Rating",
       y = NULL,
       x = NULL) +
  ylim(0, 5)

funnywords %>% 
ggplot(aes(label = word, size = n, color = n)) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 8)

```


```{r}
wordcloud2(funnywords, backgroundColor = "black")  
```



```{r Action}
subset(data.w.genre.ratings, Action == 1) %>% 
  arrange(desc(avg_rating)) %>% 
  slice(1:5) %>% 
  ggplot(aes(original_title, avg_rating, label = round(avg_rating, 2))) +
  geom_point(color = "red") +
  geom_label(color = "red", vjust = -0.5) +
  labs(title = "Top 5 Action Movies by Average IMDB User Rating",
       y = NULL,
       x = NULL) +
  ylim(0, 5)

 
actionwords %>% 
ggplot(aes(label = word, size = n, color = n)) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 8) 

```


```{r, fig.show='asis'}

```



```{r Drama}
subset(data.w.genre.ratings, Drama == 1) %>% 
  arrange(desc(avg_rating)) %>% 
  slice(1:5) %>% 
  ggplot(aes(original_title, avg_rating, label = round(avg_rating, 2))) +
  geom_point(color = "red") +
  geom_label(color = "red", vjust = -0.5) +
  labs(title = "Top 5 Drama Movies by Average IMDB User Rating",
       y = NULL,
       x = NULL) +
  ylim(0, 5) +
  transition_states(original_title)


dramawords %>% 
ggplot(aes(label = word, size = n, color = n)) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 8)

```

```{r}

```


```{r Thriller}
subset(data.w.genre.ratings, Thriller == 1) %>% 
  arrange(desc(avg_rating)) %>% 
  slice(1:5) %>% 
  ggplot(aes(original_title, avg_rating, label = round(avg_rating, 2))) +
  geom_point(color = "red") +
  geom_label(color = "red", vjust = -0.5) +
  labs(title = "Top 5 Thriller Movies by Average IMDB User Rating",
       y = NULL,
       x = NULL) +
  ylim(0, 5)


thrillwords %>% 
ggplot(aes(label = word, size = n, color = n)) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 8)


```

```{r}

```







```{r, include = FALSE}
ggplot(AcadSelfData, aes(true_self, fill = true_self)) +
  geom_bar(show.legend = FALSE) +
  geom_text(aes(label = ..count..), stat = "count", vjust = -0.5, color = gtx) +
  labs(title = "My major is a reflection of my true self.",
       x = NULL,
       y = NULL) +
  scale_fill_viridis(discrete = TRUE,
                     option = "E") +
  ylim(0, 275)



ggplot(AcadSelfData, aes(fulfilled, fill = fulfilled)) +
  geom_bar(show.legend = FALSE) +
  geom_text(aes(label = ..count..), stat = "count", vjust = -0.5, color = gtx) +
  labs(title = "How fulfilled do you feel in your major?",
       x = NULL,
       y = NULL) +
  scale_fill_viridis(discrete = TRUE,
                     option = "E") +
  ylim(0, 300)



ggplot(AcadSelfData, aes(fit_in, fill = fit_in)) +
  geom_bar(show.legend = FALSE) +
  geom_text(aes(label = ..count..), stat = "count", vjust = -0.5, color = gtx) +
  labs(title = "I feel like I fit in easily with other students in my major.",
       x = NULL,
       y = NULL) +
  scale_fill_viridis(discrete = TRUE,
                     option = "E") +
  ylim(0, 225)



ggplot(AcadSelfData, aes(overall_satisfied, fill = overall_satisfied)) +
  geom_bar(show.legend = FALSE) +
  geom_text(aes(label = ..count..), stat = "count", vjust = -0.5, color = gtx) +
  labs(title = "Overall, How satisfied or unsatisfied are you\nwith your college academic experience?",
       x = NULL,
       y = NULL) +
  scale_fill_viridis(discrete = TRUE,
                     option = "E") +
  ylim(0, 350)




ggplot(AcadSelfData, aes(rewarding, fill = rewarding)) +
  geom_bar(show.legend = FALSE) +
  geom_text(aes(label = ..count..), stat = "count", vjust = -0.5, color = gtx) +
  labs(title = "Being a student is a rewarding experience.",
       x = NULL,
       y = NULL) +
  scale_fill_viridis(discrete = TRUE,
                     option = "E") +
  ylim(0, 225)




ggplot(AcadSelfData, aes(money_issue, fill = money_issue)) +
  geom_bar(show.legend = FALSE) +
  geom_text(aes(label = ..count..), stat = "count", vjust = -0.5, color = gtx) +
  labs(title = "If money were not an issue, I would have chosen a different major.",
       x = NULL,
       y = NULL) +
  scale_fill_viridis(discrete = TRUE,
                     option = "E") +
  ylim(0, 275)




```
