---
title: "Exploring IMDB Movie Ratings"
author: "Silas Jackson"
date: "5/6/2021"
summary: An exploration of the IMDB Movies dataset with ratings, genre, and keywords.
slug: movie-data-project
linktitle: "Movie Rating Dataset"
output:
  blogdown::html_page:
    
    toc: true
menu:
  project:
    parent: Projects
    weight: 5
type: docs
editor_options: 
  chunk_output_type: inline
lastmod: '2021-04-24T23:09:32-04:00'
shiny: true
---

# **Overview**

## **Research Questions**

## **Methods**

### Dataset

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r Libraries, include = FALSE}
library(tidyverse)
library(jsonlite)
library(lubridate)
library(tm)  
library(viridis)

library(vapoRwave)
library(plotly)
library(ggwordcloud)
library(wordcloud)
library(wordcloud2)
library(ggthemes)

library(extrafont)
library(gganimate)
library(ggpubr)
library(png)
library(stringr)
library(cowplot)

library(magick)
library(gridExtra)
library(jpeg)
library(tidytext)
library(tm)
library(pacman)
library(grid)
library(gridExtra)


windowsFonts("a dripping marker" = windowsFont("a dripping marker"))
```

```{r Load Data, include = FALSE}

load("Movies_Data.Rdata")

```



```{r Theme Setup, include = FALSE}
mytheme <- theme(text = element_text(color = "white"),
                 plot.title = element_text(family = "Rockwell", size = 15, face = "bold"),
                 plot.title.position = "plot",
                 plot.background = element_rect(fill = "black"),
                 panel.background = element_rect(fill = "black"),
                 legend.background = element_blank(),
                 legend.key = element_blank(),
                 legend.box.background = element_blank(),
                 panel.grid.major.x = element_blank(),
                 panel.grid.minor.x = element_blank(),
                 panel.grid.major.y = element_line(linetype = "dotted", color = "grey90"),
                 panel.grid.minor.y = element_line(linetype = "dashed", color = "grey30"),
                 axis.text = element_text(color = "white", size = 8))

theme_set(mytheme)


centfox <- c("#F88334", "#E27E5C", "#B86B68",
             "#472345", "#150B4B")  
```





```{r Explore All Movies}
ggplot(data.w.genre.ratings[order(release_year),.N, by=release_year], 
      aes(x=release_year, y=N, fill =  release_year)) + 
  geom_bar(stat="identity", show.legend = FALSE)+ 
  labs(title = "Movies by Release Year",
        x = NULL,
        y = NULL) +
  scale_fill_gradientn(colors = centfox) +
  theme(text = element_text(family = "Broadway"),
        plot.title = element_text(family = "Broadway"))

```



```{r 70s Setup, inclde = FALSE}
seventies <- subset(data.w.genre.ratings, release_decade == 1970)


col70s <- c("#75c8ae", "#5a3d2b", "#ffecb4", "#e5771e", "#f4a127")
col70s <- colorRampPalette(col70s)(10)



imgfile <- "plotpic.jpg"

pict <- jpeg::readJPEG(imgfile)


```


```{r 70s}

plot70s1 <- seventies %>% 
  arrange(desc(budget)) %>% 
  slice(1:10) %>% 
  ggplot(aes(original_title, budget, fill = original_title)) +
  annotation_custom(rasterGrob(pict, 
                               width = unit(1,"npc"), 
                               height = unit(1,"npc")), 
                    -Inf, Inf, -Inf, Inf) +
  geom_col(show.legend = FALSE) +
  labs(title = "Top 10 70s Movies with Highest Budgets",
       x = NULL,
       y = NULL) +
  scale_fill_manual(values = col70s) +
  theme_cowplot() +
  theme(text = element_text(family = "Rockwell", color = "white"),
        axis.text.x = element_text(family = "Rockwell", color = "white"),
        axis.text.y = element_text(family = "Rockwell", color = "white"),
        plot.title = element_text(family = "Rockwell", size = 15, face = "bold"),
        plot.title.position = "plot",
        legend.background = element_blank(),
        legend.key = element_blank(),
        legend.box.background = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(linetype = "dotted", color = "grey90"),
        panel.grid.minor.y = element_line(linetype = "dashed", color = "grey30"),
        axis.text = element_text(color = "white", size = 8)) +
  scale_x_discrete(labels = function(x) str_wrap(str_replace_all(x, "foo" , " "),
                                                 width = 20))


ggdraw() +
  draw_image(pict, scale = 2) +
  draw_plot(plot70s1)



plot70s2 <- seventies %>% 
  arrange(desc(revenue)) %>% 
  slice(1:10) %>% 
  ggplot(aes(original_title, revenue, fill = original_title)) +
  annotation_custom(rasterGrob(pict, 
                               width = unit(1,"npc"), 
                               height = unit(1,"npc")), 
                    -Inf, Inf, -Inf, Inf) +
  geom_col(show.legend = FALSE) +
  labs(title = "Top 10 70s Movies by Revenue",
       x = NULL,
       y = NULL) +
  scale_fill_manual(values = col70s) +
  theme_cowplot() +
  theme(text = element_text(family = "Rockwell", color = "white"),
        axis.text.x = element_text(family = "Rockwell", color = "white"),
        axis.text.y = element_text(family = "Rockwell", color = "white"),
        plot.title = element_text(family = "Rockwell", size = 15, face = "bold"),
        plot.title.position = "plot",
        legend.background = element_blank(),
        legend.key = element_blank(),
        legend.box.background = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(linetype = "dotted", color = "grey90"),
        panel.grid.minor.y = element_line(linetype = "dashed", color = "grey30"),
        axis.text = element_text(color = "white", size = 8)) +
  scale_x_discrete(labels = function(x) str_wrap(str_replace_all(x, "foo" , " "),
                                                 width = 20))

ggdraw() +
  draw_image(pict, scale = 2) +
  draw_plot(plot70s2)


plot70s3 <- seventies %>% 
  arrange(desc(popularity)) %>% 
  slice(1:10) %>% 
  ggplot(aes(original_title, popularity, fill = original_title)) +
  annotation_custom(rasterGrob(pict, 
                               width = unit(1,"npc"), 
                               height = unit(1,"npc")), 
                    -Inf, Inf, -Inf, Inf) +
  geom_col(show.legend = FALSE) +
  labs(title = "Top 10 70s Movies by Popularity",
       x = NULL,
       y = NULL) +
  scale_fill_manual(values = col70s) +
  theme_cowplot() +
  theme(text = element_text(family = "Rockwell", color = "white"),
        axis.text.x = element_text(family = "Rockwell", color = "white"),
        axis.text.y = element_text(family = "Rockwell", color = "white"),
        plot.title = element_text(family = "Rockwell", size = 15, face = "bold"),
        plot.title.position = "plot",
        legend.background = element_blank(),
        legend.key = element_blank(),
        legend.box.background = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(linetype = "dotted", color = "grey90"),
        panel.grid.minor.y = element_line(linetype = "dashed", color = "grey30"),
        axis.text = element_text(color = "white", size = 8)) +
  scale_x_discrete(labels = function(x) str_wrap(str_replace_all(x, "foo" , " "),
                                                 width = 20))


ggdraw() +
  draw_image(pict, scale = 2) +
  draw_plot(plot70s3)

```


```{r 80s Setup, include = FALSE}
eighties <- subset(data.w.genre.ratings, release_decade == 1980)


scales::show_col(vapoRwave:::macPlus_palette)
mycolors <- colorRampPalette(vapoRwave:::macPlus_palette)(10)
```



```{r 80s}
eighties %>% 
  arrange(desc(budget)) %>% 
  slice(1:10) %>% 
  ggplot(aes(original_title, budget, fill = original_title)) +
  geom_col(show.legend = FALSE) +
  labs(title = "Top 10 80s Movies by Budget",
       x = NULL,
       y = "Budget") +
  scale_x_discrete(labels = function(x) str_wrap(str_replace_all(x, "foo" , " "),
                                                 width = 20)) +
  new_retro() +
  theme(axis.text.x = element_text(angle = 90),
    axis.title.y = element_text(angle = 90)) +
  scale_fill_manual(values = mycolors) +
  scale_x_discrete(labels = function(x) str_wrap(str_replace_all(x, "foo" , " "),
                                                 width = 20))


eighties %>% 
  arrange(desc(revenue)) %>% 
  slice(1:10) %>% 
  ggplot(aes(original_title, revenue, fill = original_title)) +
  geom_col(show.legend = FALSE) +
  labs(title = "Top 10 80s Movies by Revenue",
       x = NULL,
       y = "Revenue") +
  scale_x_discrete(labels = function(x) str_wrap(str_replace_all(x, "foo" , " "),
                                                 width = 20)) +
  new_retro() +
  theme(axis.text = element_text(angle = 90),
    axis.title.y = element_text(angle = 90)) +
  scale_fill_manual(values = mycolors)

eighties %>% 
  arrange(desc(popularity)) %>% 
  slice(1:10) %>% 
  ggplot(aes(original_title, popularity, fill = original_title)) +
  geom_col(show.legend = FALSE) +
  labs(title = "Top 10 80s Movies by Popularity",
       x = NULL) +
  scale_x_discrete(labels = function(x) str_wrap(str_replace_all(x, "foo" , " "),
                                                 width = 20)) +
  new_retro() +
  theme(axis.title.y = element_text(angle = 90),
        axis.text.x = element_text(angle = 90)) +
  scale_fill_manual(values = mycolors)

```


```{r 90s Setup, include = FALSE}

nineties <- subset(data.w.genre.ratings, release_decade == 1990)
col90s <- c("#D30166", "#222074", "#9982AE",
            "#FFFFFF", "#BF0404", "#05889A",
            "#FFBB11", "#38cd2c", "#F2E205",
            "#6F1067")
```



```{r 90s}
nineties %>% 
  arrange(desc(budget)) %>% 
  slice(1:10) %>% 
  ggplot(aes(original_title, budget, fill = original_title)) +
  geom_col(show.legend = FALSE) +
  labs(title = "Top 10 90s Movies by Budget",
       x = NULL,
       y = "Budget") +
  theme(axis.text = element_text(family = "Times New Roman",
                            color = "skyblue", 
                            angle = 90, size = 10),
        axis.title = element_text(family = "Times New Roman",
                                  size = 12, face = "bold",
                                  color = "skyblue"),
    plot.title = element_text(family = "a dripping marker",
                                  color = "#38cd2c",
                                  size = 40),
        plot.title.position = "plot") +
  scale_fill_manual(values = col90s) +
  scale_x_discrete(labels = function(x) str_wrap(str_replace_all(x, "foo" , " "),
                                                 width = 20))





nineties %>% 
  arrange(desc(revenue)) %>% 
  slice(1:10) %>% 
  ggplot(aes(original_title, revenue, fill = original_title)) +
  geom_col(show.legend = FALSE) +
  labs(title = "Top 10 90s Movies by Revenue",
       x = NULL,
       y = "Revenue") +
  theme(axis.text = element_text(family = "Times New Roman",
                            color = "skyblue",
                            angle = 90, size = 10),
        axis.title = element_text(family = "Times New Roman",
                                  size = 12, face = "bold",
                                  color = "skyblue"),
    plot.title = element_text(family = "a dripping marker",
                                  color = "#38cd2c",
                                  size = 40),
        plot.title.position = "plot") +
  scale_fill_manual(values = col90s) +
  scale_x_discrete(labels = function(x) str_wrap(str_replace_all(x, "foo" , " "),
                                                 width = 20))




nineties %>% 
  arrange(desc(popularity)) %>% 
  slice(1:10) %>% 
  ggplot(aes(original_title, popularity, fill = original_title)) +
  geom_col(show.legend = FALSE) +
  labs(title = "Top 10 90s Movies by Popularity",
       x = NULL,
       y = NULL) +
  theme(axis.text = element_text(family = "Times New Roman",
                            color = "skyblue",
                            angle = 90,
                            size = 10),
        axis.title = element_text(family = "Times New Roman",
                                  size = 12, face = "bold",
                                  color = "skyblue"),
    plot.title = element_text(family = "a dripping marker",
                                  color = "#38cd2c",
                                  size = 40),
        plot.title.position = "plot") +
  scale_fill_manual(values = col90s) +
  scale_x_discrete(labels = function(x) str_wrap(str_replace_all(x, "foo" , " "),
                                                 width = 20))




```




```{r 2000s Setup}

twothousands <- subset(data.w.genre.ratings, release_decade >= 2000)

```




```{r 2000s}

twothousands %>% 
  arrange(desc(budget)) %>% 
  slice(1:10) %>% 
  ggplot(aes(original_title, budget, fill = original_title)) +
  geom_col(show.legend = FALSE) +
  labs(title = "Top 10 2000s Movies by Budget",
       x = NULL,
       y = NULL)


twothousands %>% 
  arrange(desc(revenue)) %>% 
  slice(1:10) %>% 
  ggplot(aes(original_title, revenue, fill = original_title)) +
  geom_col(show.legend = FALSE) +
  labs(title = "Top 10 2000s Movies by Revenue",
       x = NULL,
       y = NULL)



twothousands %>% 
  arrange(desc(popularity)) %>% 
  slice(1:10) %>% 
  ggplot(aes(original_title, popularity, fill = original_title)) +
  geom_col(show.legend = FALSE) +
  labs(title = "Top 10 2000s Movies by Popularity",
       x = NULL,
       y = NULL)

```





```{r Horror, message = FALSE, warning = FALSE}

bloody <- c("#8b0202", "#a51515", "#d1001d", "#660000",
            "#b5b69c", "#7d7e73", "#876969",
            "#6d4141", "#422020")

spooky <- colorRampPalette(bloody)(35)


subset(data.w.genre.ratings, Horror == 1) %>% 
  arrange(desc(avg_rating)) %>% 
  slice(1:5) %>% 
  ggplot(aes(original_title, avg_rating, label = original_title)) +
  geom_point(show.legend = FALSE, color = "red", stroke = 2) +
  geom_segment(aes(x = original_title, xend=original_title, y = 0, yend = avg_rating), color = "red") +
  geom_label(color = "red", vjust = -0.5, label.size = 1, show.legend = FALSE, fill = "black") +
  labs(title = "Top 5 Horror Movies by Average IMDB User Rating",
       y = NULL,
       x = NULL) +
  ylim(0, 5) +
  scale_fill_manual(values = bloody) +
  theme(text = element_text(family = "Broadway", size = 15),
    plot.title = element_text(family = "Chiller", size = 25),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_line(linetype = "dashed", color = "#A9A9A9")) +
  scale_x_discrete(labels = function(x) str_wrap(str_replace_all(x, "foo" , " "),
                                                 width = 20)) +
  transition_states(original_title, transition_length = 5, state_length = 5)


scarywords %>% 
ggplot(aes(label = word, size = n, color = as.factor(n), size = n)) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 20) +
  scale_color_manual(values = spooky)
```

```{r}
wordcloud2(scarywords, backgroundColor = "black", color = spooky)  
```





```{r Romance}
lovey <- c("#fe7f6c", "#fec1b2", "#fbc8d6", "#f0a1a5", "#f70424", "#cda34f", "#c4146c",
           "#ffc3a0", "#fffbd7", "#b6fcd5",
           "#b46d75", "#c08485", "#f1d19b", "#d9a380")

dovey <- colorRampPalette(lovey)(74)


subset(data.w.genre.ratings, Romance == 1) %>%
  arrange(desc(avg_rating)) %>% 
  slice(1:3) %>% 
  ggplot(aes(original_title, avg_rating, label = original_title)) +
  geom_point(color = "hotpink", shape = 8, stroke = 2) +
  geom_label(color = "hotpink", vjust = -0.5) +
  labs(title = "Top 3 Romance Movies by Average IMDB User Rating",
       y = NULL,
       x = NULL) +
  ylim(0, 5) +
  scale_fill_manual(values = lovey) +
  theme(text = element_text(family = "Broadway", size = 15),
    plot.title = element_text(family = "Broadway", size = 15),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_line(linetype = "dashed", color = "#A9A9A9")) +
  scale_x_discrete(labels = function(x) str_wrap(str_replace_all(x, "foo" , " "),
                                                 width = 20)) +
  transition_states(original_title, transition_length = 5, state_length = 5)


lovewords %>% 
ggplot(aes(label = word, size = n, color = as.factor(n), size = n)) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 25) +
  scale_color_manual(values = dovey)

```

```{r}
wordcloud2(lovewords, backgroundColor = "black", color = dovey)  
```



```{r Comedy}
subset(data.w.genre.ratings, Comedy == 1) %>% 
  arrange(desc(avg_rating)) %>% 
  slice(1:5) %>% 
  ggplot(aes(original_title, avg_rating, label = round(avg_rating, 2))) +
  geom_point(color = "blue") +
  geom_label(color = "blue", vjust = -0.5) +
  labs(title = "Top 5 Comedy Movies by Average IMDB User Rating",
       y = NULL,
       x = NULL) +
  ylim(0, 5) +
  transition_states(original_title)

funnywords %>% 
ggplot(aes(label = word, size = n, color = n)) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 8)

```


```{r}
wordcloud2(funnywords)  
```



```{r Action}
subset(data.w.genre.ratings, Action == 1) %>% 
  arrange(desc(avg_rating)) %>% 
  slice(1:5) %>% 
  ggplot(aes(original_title, avg_rating, label = round(avg_rating, 2))) +
  geom_point(color = "red") +
  geom_label(color = "red", vjust = -0.5) +
  labs(title = "Top 5 Action Movies by Average IMDB User Rating",
       y = NULL,
       x = NULL) +
  ylim(0, 5) +
  transition_states(original_title)

 
actionwords %>% 
ggplot(aes(label = word, size = n, color = n)) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 8) 

```


```{r}
wordcloud2(actionwords)  
```



```{r Drama}
subset(data.w.genre.ratings, Drama == 1) %>% 
  arrange(desc(avg_rating)) %>% 
  slice(1:5) %>% 
  ggplot(aes(original_title, avg_rating, label = round(avg_rating, 2))) +
  geom_point(color = "red") +
  geom_label(color = "red", vjust = -0.5) +
  labs(title = "Top 5 Drama Movies by Average IMDB User Rating",
       y = NULL,
       x = NULL) +
  ylim(0, 5) +
  transition_states(original_title)


dramawords %>% 
ggplot(aes(label = word, size = n, color = n)) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 8)

```

```{r}
wordcloud2(dramawords)  
```


```{r Thriller}
subset(data.w.genre.ratings, Thriller == 1) %>% 
  arrange(desc(avg_rating)) %>% 
  slice(1:5) %>% 
  ggplot(aes(original_title, avg_rating, label = round(avg_rating, 2))) +
  geom_point(color = "red") +
  geom_label(color = "red", vjust = -0.5) +
  labs(title = "Top 5 Thriller Movies by Average IMDB User Rating",
       y = NULL,
       x = NULL) +
  ylim(0, 5) +
  transition_states(original_title)


thrillwords %>% 
ggplot(aes(label = word, size = n, color = n)) +
  geom_text_wordcloud_area() +
  scale_size_area(max_size = 8)


```

```{r}
wordcloud2(thrillwords)  
```

